backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: "articles"
    label: "Artiklar"
    files:
      - label: "Verkstad"
        name: "verkstad"
        file: "content/verkstad.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Datum", name: "date", widget: "datetime" }
          - { label: "Brödtext", name: "body", widget: "markdown" }
