site_url: https://www.lottaenocsson.se
backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: pages
    label: Page
    files:
      - label: Startsida
        name: startpage
        file: content/pages/startpage.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Text, name: body, widget: markdown }
          - label: Images
            name: images
            widget: list
            field: { label: Image, name: image, widget: image }
      - label: CV
        name: cv
        file: content/pages/cv.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Text, name: body, widget: markdown }
      - label: Skulpturer
        name: sculptures
        file: content/pages/sculptures.md
        fields:
          - { label: Title, name: title, widget: string }
          - label: Skulpturer
            name: sculptures
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Image, name: image, widget: image }
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  required: false,
                }
      - label: M책lningar
        name: paintings
        file: content/pages/paintings.md
        fields:
          - { label: Title, name: title, widget: string }
          - label: M책lningar
            name: paintings
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Image, name: image, widget: image }
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  required: false,
                }
      - label: Kontakt
        name: contact
        file: content/pages/contact.md
        fields:
          - { label: Namn, name: name, widget: string }
          - { label: Gatuadress, name: streetAddress, widget: string }
          - { label: Postnummer, name: postalCode, widget: string }
          - { label: Postort, name: city, widget: string }
          - { label: Telefonnummer, name: phoneNumber, widget: string }
          - { label: E-post, name: email, widget: string }
          - label: L채nkar
            name: links
            widget: list
            fields:
              - { label: L채nk, name: url, widget: string }
              - { label: Text, name: text, widget: string }
