backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: pages
    label: Page
    files:
      - label: Startsida
        name: startpage
        file: content/pages/startpage.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Text, name: body, widget: markdown }
          - label: Images
            name: images
            widget: list
            field: { label: Image, name: image, widget: image }
      - label: CV
        name: cv
        file: content/pages/cv.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Text, name: body, widget: markdown }
      - label: Skulpturer
        name: sculptures
        file: content/pages/sculptures.md
        fields:
          - { label: Title, name: title, widget: string }
          - label: Skulpturer
            name: sculptures
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Text, name: text, widget: string }
      - label: Målningar
        name: paintings
        file: content/pages/paintings.md
        fields:
          - { label: Title, name: title, widget: string }
          - label: Målningar
            name: paintings
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Text, name: text, widget: string }
