backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: "pages"
    label: "Sidor"
    files:
      - label: "Startsida"
        name: "startpage"
        file: "content/pages/startpage.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Introtext", name: "intro", widget: "markdown" }
